/**
 * Boat-name ideas library — the content behind /names and /names/<category>.
 *
 * Hand-curated, common-phrase names (no trademarks, film ships, or crude jokes).
 * Every name must fit the previewer's 18-character name field, so each one opens
 * straight into the transom previewer. boat-names.test.ts enforces length, dupes
 * within a category, and a minimum count per category.
 *
 * A name may appear in several categories; `allNames()` merges them.
 */
import type { FontKey } from "@/components/site/previewer-types";

export const NAME_MAX_LENGTH = 18;

export type CategorySlug =
  | "funny"
  | "fishing"
  | "sailboat"
  | "pontoon"
  | "classic"
  | "family"
  | "canadian"
  | "fast";

export interface NameCategory {
  slug: CategorySlug;
  /** Short chip label. */
  label: string;
  /** Page H1 + the search phrase the page targets. */
  heading: string;
  /** Title lead, e.g. "Funny Boat Names"; the route appends the live count. */
  titleTopic: string;
  /** Meta description. */
  description: string;
  /** Two or three sentences above the list. */
  intro: string;
  /** Letter style the names are shown in and open with in the previewer. */
  font: FontKey;
  names: string[];
}

export const CATEGORIES: NameCategory[] = [
  {
    slug: "funny",
    label: "Funny",
    heading: "Funny boat names",
    titleTopic: "Funny Boat Names",
    description:
      "Funny boat names and nautical puns, from Knot Working to Reel Therapy. Pick one and see it on a transom in vinyl or cast acrylic.",
    intro:
      "A good pun is the most popular way to name a boat — it gets a laugh at the dock and a wave on the water. The best funny names still read cleanly from a distance, so keep them short and say them out loud once before you commit.",
    font: "deck-sans",
    names: [
      "Knot Working",
      "Seas the Day",
      "Reel Therapy",
      "Aquaholic",
      "Unsinkable II",
      "Nauti Buoy",
      "Nauti Girl",
      "Ship Happens",
      "Knot on Call",
      "Liquid Asset",
      "Sea-Esta",
      "Sea Section",
      "Current Affair",
      "Pier Pressure",
      "Shore Thing",
      "Hull-arious",
      "Vitamin Sea",
      "Aboat Time",
      "Dock Holiday",
      "Wake Me Up",
      "Oh Buoy",
      "Pontoonie",
      "Tipsy Tugboat",
      "Loan Shark",
      "Kids' Inheritance",
      "Fin-ancial Plan",
      "The Office",
      "Board Meeting",
      "Out of Office",
      "Stern Warning",
      "Sea Ya Later",
      "Sail La Vie",
      "Nacho Boat",
      "Dock Tales",
      "Buoy Oh Buoy",
      "Plan Sea",
      "Yacht Now",
      "Sea Monkey",
      "Why Knot",
      "Anchor Management",
      "Aye Aye Sir",
      "My Other Car",
      "Retire-Mint",
      "Mid-Life Crisis",
      "Therapy Session",
      "Tax Write-Off",
      "Wife's Idea",
      "Husband's Idea",
      "Just Floatin'",
      "Floatin' Around",
      "Breakin' Wind",
      "Slow Poke",
      "Ctrl Alt Delete",
      "Unplugged",
      "Water You Doing",
      "Sea You Soon",
      "Shucks",
      "Moor Money",
    ],
  },
  {
    slug: "fishing",
    label: "Fishing",
    heading: "Fishing boat names",
    titleTopic: "Fishing Boat Names",
    description:
      "Fishing boat names for bass boats, walleye rigs and offshore sportfishers. See your favourite on a transom before you order the lettering.",
    intro:
      "Fishing boats earn the best names — half brag, half confession. Tournament boats and trailered rigs often carry the name on both sides of the hull, so check the letter height against the panel you actually have.",
    font: "commodore",
    names: [
      "Reel Therapy",
      "Reel Deal",
      "Reel Time",
      "Reel Busy",
      "Reel Estate",
      "Reel Escape",
      "Knot Biting",
      "Fish Tales",
      "Fishful Thinking",
      "Bait & Switch",
      "Hooked",
      "Hooked on Sonar",
      "Hook, Line",
      "Off the Hook",
      "Catch 22",
      "Catch & Release",
      "Gone Fishin'",
      "Fish On",
      "Fin Chaser",
      "Walleye Wagon",
      "Bass Master",
      "Bass Ackwards",
      "Musky Madness",
      "Pike Place",
      "Trout Scout",
      "Salmon Chanted",
      "Perch Perfect",
      "Sonar Sunrise",
      "Dawn Patrol",
      "First Light",
      "Early Bite",
      "Limit Out",
      "The Honey Hole",
      "Secret Spot",
      "Lucky Lure",
      "Tackle Box",
      "Drift Away",
      "Trolling Stone",
      "Troller Coaster",
      "Cast Away",
      "Castaway",
      "Fish Whisperer",
      "Shore Lunch",
      "Livewell",
      "Net Worth",
      "Tight Lines",
      "Screaming Reel",
      "Bent Rod",
      "Weekend Catch",
      "Early Retirement",
      "The Other Woman",
      "Sick Day",
      "Fish Finder",
      "Bottom Feeder",
      "Knot Home",
    ],
  },
  {
    slug: "sailboat",
    label: "Sailboat",
    heading: "Sailboat names",
    titleTopic: "Sailboat Names",
    description:
      "Sailboat names inspired by wind, weather and passage-making. Try one in a classic serif or script on your transom before you commit.",
    intro:
      "Sailors tend toward names about wind, weather and the long way round. A sailboat's name is also said over the VHF radio, so a short, clear name that can't be misheard is worth more than a clever long one.",
    font: "transom-serif",
    names: [
      "Fair Winds",
      "Second Wind",
      "Trade Winds",
      "Following Seas",
      "Windward",
      "Leeward",
      "Close Hauled",
      "Beam Reach",
      "Broad Reach",
      "Wing and Wing",
      "Heeling Time",
      "True North",
      "Due North",
      "Northern Star",
      "Pole Star",
      "Wanderlust",
      "Windfall",
      "Wind Song",
      "Wind Dancer",
      "Sea Breeze",
      "Zephyr",
      "Mistral",
      "Sirocco",
      "Halcyon",
      "Serendipity",
      "Odyssey",
      "Voyager",
      "Passage",
      "Meridian",
      "Latitude",
      "Longitude",
      "Compass Rose",
      "Starboard Tack",
      "Port of Call",
      "Blue Water",
      "Bluewater Bound",
      "Horizon",
      "Blue Horizon",
      "Far Horizons",
      "Kindred Spirit",
      "Free Spirit",
      "Wind Rider",
      "Sail Away",
      "Sea Gypsy",
      "Moonshadow",
      "Moonlight Sail",
      "Evening Star",
      "Stargazer",
      "Nomad",
      "Gypsy Wind",
      "Albatross",
      "Petrel",
      "Osprey",
      "Tern Around",
    ],
  },
  {
    slug: "pontoon",
    label: "Pontoon",
    heading: "Pontoon boat names",
    titleTopic: "Pontoon Boat Names",
    description:
      "Pontoon boat names for party barges, tritoons and cottage cruisers. Preview the name on your boat in vinyl or cast acrylic.",
    intro:
      "Pontoons are for slow afternoons, full coolers and the whole family aboard, and the names usually say so. Pontoon fences and tritoon transoms are wide, so there's room for a longer name at a readable height.",
    font: "deck-sans",
    names: [
      "Pontoonie",
      "Party Barge",
      "Party Pontoon",
      "Pontoon Saloon",
      "Toon Town",
      "Tritoon Tycoon",
      "Happy Hour",
      "Cocktail Cruise",
      "Sunset Cruiser",
      "Sunset Sipper",
      "Floating Porch",
      "Floating Patio",
      "The Living Room",
      "Lake Lounge",
      "Lake Life",
      "Lake Effect",
      "Lake Therapy",
      "Lakeside Lounge",
      "Slow Ride",
      "Slow Motion",
      "No Wake Zone",
      "Idle Time",
      "Lazy Days",
      "Lazy Daze",
      "Summer Daze",
      "Sunday Funday",
      "Weekend Warrior",
      "Pour Decisions",
      "Wine Down",
      "Wine Not",
      "Shore Leave",
      "Sandbar Social",
      "Cove Party",
      "Just Floatin'",
      "Floatin' Around",
      "Floaty McFloat",
      "Chill Barge",
      "Cooler Cruiser",
      "Brew Crew",
      "Knot Rushing",
      "Grandpa's Barge",
      "Nana's Navy",
      "Pontoon Life",
      "Toon Around",
      "Deck the Hulls",
      "Anchors Aweigh",
      "The Dock Bar",
      "Nap Time",
      "Happy Place",
      "Lake Please",
    ],
  },
  {
    slug: "classic",
    label: "Classic",
    heading: "Classic boat names",
    titleTopic: "Classic Boat Names",
    description:
      "Classic and elegant boat names for cruisers, yachts and wooden boats. See them in script or serif lettering on a real transom.",
    intro:
      "Classic names never date: virtues, stars, old words for the sea. They suit dimensional acrylic in a script or serif face, and they sound right on the radio and on a hailing-port line.",
    font: "yacht-script",
    names: [
      "Serenity",
      "Tranquility",
      "Solitude",
      "Grace",
      "Amazing Grace",
      "Liberty",
      "Freedom",
      "Independence",
      "Endeavour",
      "Resolute",
      "Intrepid",
      "Valiant",
      "Tenacity",
      "Perseverance",
      "Destiny",
      "Providence",
      "Harmony",
      "Reverie",
      "Aurora",
      "Celeste",
      "Stella Maris",
      "Aquila",
      "Orion",
      "Polaris",
      "Vega",
      "Nautilus",
      "Neptune",
      "Poseidon",
      "Calypso",
      "Athena",
      "Sea Spirit",
      "Sea Dream",
      "Seabird",
      "Sea Fever",
      "Silver Lining",
      "Silver Moon",
      "Blue Moon",
      "Island Time",
      "Pearl",
      "Sapphire",
      "Emerald Isle",
      "Obsession",
      "Elegance",
      "Belle",
      "Belle Époque",
      "Joie de Vivre",
      "Carpe Diem",
      "Dolce Vita",
      "Bon Voyage",
      "Pura Vida",
      "Mañana",
      "Aloha",
      "Mariner",
      "Heritage",
    ],
  },
  {
    slug: "family",
    label: "Couples & family",
    heading: "Boat names for couples and families",
    titleTopic: "Boat Names for Couples & Families",
    description:
      "Boat names for couples, families and inherited boats — sentimental, funny and everything between. Preview any name on your transom.",
    intro:
      "Plenty of boats are named for the people aboard: a partner, the kids, a parent who owned her first. Two first names joined with an ampersand is a classic format — just check the run length, because two names add up fast.",
    font: "commodore-italic",
    names: [
      "Our Time",
      "Our Escape",
      "Two of Us",
      "Just Us",
      "Us Two",
      "Better Together",
      "Happily Ever After",
      "Second Chance",
      "Second Act",
      "Second Honeymoon",
      "Empty Nest",
      "Nest Egg",
      "Family Ties",
      "Family Affair",
      "Kids' Inheritance",
      "Dad's Toy",
      "Mom's Turn",
      "Grandpa's Pride",
      "Nana's Navy",
      "Papa's Pride",
      "Legacy",
      "Heirloom",
      "Dad's Dream",
      "Dream Come True",
      "Dream Weaver",
      "Sweet Escape",
      "Sweet Pea",
      "Sweetwater",
      "Honey Do",
      "Honey Don't",
      "Her Idea",
      "His Idea",
      "Her Turn",
      "Yes Dear",
      "Blessed",
      "Grateful",
      "Forever Young",
      "Young at Heart",
      "Three Sisters",
      "Brothers Three",
      "Four Winds",
      "Crew of Five",
      "Full House",
      "Home Port",
      "Home Away",
      "Anniversary",
      "Always & Forever",
      "Soulmates",
      "Two Hearts",
      "Lucky Us",
    ],
  },
  {
    slug: "canadian",
    label: "Canadian",
    heading: "Canadian boat names",
    titleTopic: "Canadian Boat Names",
    description:
      "Canadian boat names inspired by the Great Lakes, cottage country and the North. Design yours online and ship it anywhere in Canada.",
    intro:
      "Names for boats that live on Canadian water — cottage lakes, the Great Lakes, Georgian Bay and the long northern summer. Many owners pair a name like these with their home lake or town on the hailing-port line.",
    font: "transom-serif",
    names: [
      "True North",
      "Strong & Free",
      "Northern Star",
      "Northern Lights",
      "Aurora Borealis",
      "Great White North",
      "Due North",
      "North Wind",
      "Maple Leaf",
      "Maple Syrup",
      "Canuck",
      "Eh Team",
      "Sorry Aboot That",
      "Two-Four",
      "Poutine Machine",
      "Loonie",
      "Toonie",
      "The Loon",
      "Loon Call",
      "Loon Lake",
      "Whisky Jack",
      "Beaver Tail",
      "Moose Crossing",
      "Muskoka Chair",
      "Cottage Country",
      "Up North",
      "Cottage Time",
      "Dock Days",
      "Long Weekend",
      "May Two-Four",
      "Civic Holiday",
      "Canoe Envy",
      "Portage",
      "Voyageur",
      "Trapper",
      "Birch Bark",
      "Shield Rock",
      "Georgian Belle",
      "Bay Breeze",
      "Superior",
      "Lake Superior",
      "Huronia",
      "Great Laker",
      "Fresh Water",
      "Sweetwater Sea",
      "Thousand Islands",
      "Lock Hopper",
      "Island Hopper",
      "Midnight Sun",
    ],
  },
  {
    slug: "fast",
    label: "Fast boats",
    heading: "Speedboat and wake boat names",
    titleTopic: "Speedboat Names",
    description:
      "Names for speedboats, bowriders, wake boats and PWCs — fast, loud and a little cocky. See yours on the transom before you order.",
    intro:
      "Fast boats get bold names in bold letters. A condensed, heavy face reads best at speed, and wake boats with busy transoms often suit a shorter name at a larger height.",
    font: "commodore",
    names: [
      "Full Throttle",
      "Wide Open",
      "Hammer Down",
      "Pedal Down",
      "Need for Speed",
      "Top Speed",
      "Mach One",
      "Afterburner",
      "Nitro",
      "Adrenaline",
      "Rush Hour",
      "Rocket",
      "Bullet",
      "Blur",
      "Warp Speed",
      "Light Speed",
      "Overdrive",
      "Turbo",
      "Thunder",
      "Thunderstruck",
      "Lightning",
      "Storm Chaser",
      "Wave Rider",
      "Wake Maker",
      "Wake Up Call",
      "Wake Me Up",
      "Make Waves",
      "Making Waves",
      "Big Wake",
      "Rooster Tail",
      "Spray Day",
      "Hot Pursuit",
      "Outrun",
      "No Brakes",
      "Knot Slowing",
      "Catch Me",
      "Eat My Wake",
      "See Ya",
      "Gone",
      "Outta Here",
      "Wind Burn",
      "Velocity",
      "Momentum",
      "Kinetic",
      "Torque",
      "Horsepower",
      "Twin Turbo",
      "Missile",
      "Viper",
      "Stingray",
      "Barracuda",
    ],
  },
];

export function getCategory(slug: string): NameCategory | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export interface NameEntry {
  name: string;
  categories: CategorySlug[];
}

/** Every distinct name across the library, alphabetical, with its categories. */
export function allNames(): NameEntry[] {
  const byName = new Map<string, NameEntry>();
  for (const cat of CATEGORIES) {
    for (const name of cat.names) {
      const entry = byName.get(name) ?? { name, categories: [] };
      if (!entry.categories.includes(cat.slug)) entry.categories.push(cat.slug);
      byName.set(name, entry);
    }
  }
  return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name, "en"));
}

/** Previewer link that opens this name in the given letter style. */
export function previewHref(name: string, font: FontKey): string {
  const p = new URLSearchParams({ name, font });
  return `/?${p.toString()}#previewer`;
}
