/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NamesRouteImport } from './routes/names'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryHolyShipRouteImport } from './routes/gallery/holy-ship'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminOrdersIdStatusRouteImport } from './routes/api/admin/orders.$id.status'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryHolyShipRoute = GalleryHolyShipRouteImport.update({
  id: '/gallery/holy-ship',
  path: '/gallery/holy-ship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersIdStatusRoute = ApiAdminOrdersIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiAdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/api/admin/orders'
    | '/api/admin/orders/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/api/admin/orders'
    | '/api/admin/orders/$id/status'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/api/admin/orders'
    | '/api/admin/orders/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  NamesRoute: typeof NamesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  GalleryHolyShipRoute: typeof GalleryHolyShipRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/holy-ship': {
      id: '/gallery/holy-ship'
      path: '/gallery/holy-ship'
      fullPath: '/gallery/holy-ship'
      preLoaderRoute: typeof GalleryHolyShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/$id/status': {
      id: '/api/admin/orders/$id/status'
      path: '/$id/status'
      fullPath: '/api/admin/orders/$id/status'
      preLoaderRoute: typeof ApiAdminOrdersIdStatusRouteImport
      parentRoute: typeof ApiAdminOrdersRoute
    }
  }
}

interface ApiAdminOrdersRouteChildren {
  ApiAdminOrdersIdStatusRoute: typeof ApiAdminOrdersIdStatusRoute
}

const ApiAdminOrdersRouteChildren: ApiAdminOrdersRouteChildren = {
  ApiAdminOrdersIdStatusRoute: ApiAdminOrdersIdStatusRoute,
}

const ApiAdminOrdersRouteWithChildren = ApiAdminOrdersRoute._addFileChildren(
  ApiAdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  NamesRoute: NamesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  GalleryHolyShipRoute: GalleryHolyShipRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
