/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quote': typeof ApiQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/api/health' | '/api/quote'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/api/health' | '/api/quote'
  id: '__root__' | '/' | '/sitemap.xml' | '/api/health' | '/api/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQuoteRoute: ApiQuoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
