/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NamesRouteImport } from './routes/names'
import { Route as InstallRouteImport } from './routes/install'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderThankYouRouteImport } from './routes/order.thank-you'
import { Route as GalleryHolyShipRouteImport } from './routes/gallery/holy-ship'
import { Route as ApiQuoteRouteImport } from './routes/api/quote'
import { Route as ApiPriceRouteImport } from './routes/api/price'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'
import { Route as ApiOrdersApproveRouteImport } from './routes/api/orders.approve'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminOrdersIdStatusRouteImport } from './routes/api/admin/orders.$id.status'
import { Route as ApiAdminOrdersIdSendProofRouteImport } from './routes/api/admin/orders.$id.send-proof'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderThankYouRoute = OrderThankYouRouteImport.update({
  id: '/order/thank-you',
  path: '/order/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryHolyShipRoute = GalleryHolyShipRouteImport.update({
  id: '/gallery/holy-ship',
  path: '/gallery/holy-ship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRoute = ApiQuoteRouteImport.update({
  id: '/api/quote',
  path: '/api/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceRoute = ApiPriceRouteImport.update({
  id: '/api/price',
  path: '/api/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersApproveRoute = ApiOrdersApproveRouteImport.update({
  id: '/api/orders/approve',
  path: '/api/orders/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersIdStatusRoute = ApiAdminOrdersIdStatusRouteImport.update({
  id: '/$id/status',
  path: '/$id/status',
  getParentRoute: () => ApiAdminOrdersRoute,
} as any)
const ApiAdminOrdersIdSendProofRoute =
  ApiAdminOrdersIdSendProofRouteImport.update({
    id: '/$id/send-proof',
    path: '/$id/send-proof',
    getParentRoute: () => ApiAdminOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/price': typeof ApiPriceRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/orders/approve': typeof ApiOrdersApproveRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/admin/orders/$id/send-proof': typeof ApiAdminOrdersIdSendProofRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/price': typeof ApiPriceRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/orders/approve': typeof ApiOrdersApproveRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/admin/orders/$id/send-proof': typeof ApiAdminOrdersIdSendProofRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/install': typeof InstallRoute
  '/names': typeof NamesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/api/price': typeof ApiPriceRoute
  '/api/quote': typeof ApiQuoteRoute
  '/gallery/holy-ship': typeof GalleryHolyShipRoute
  '/order/thank-you': typeof OrderThankYouRoute
  '/api/admin/orders': typeof ApiAdminOrdersRouteWithChildren
  '/api/orders/approve': typeof ApiOrdersApproveRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/admin/orders/$id/send-proof': typeof ApiAdminOrdersIdSendProofRoute
  '/api/admin/orders/$id/status': typeof ApiAdminOrdersIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/api/price'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/order/thank-you'
    | '/api/admin/orders'
    | '/api/orders/approve'
    | '/api/stripe/webhook'
    | '/api/admin/orders/$id/send-proof'
    | '/api/admin/orders/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/api/price'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/order/thank-you'
    | '/api/admin/orders'
    | '/api/orders/approve'
    | '/api/stripe/webhook'
    | '/api/admin/orders/$id/send-proof'
    | '/api/admin/orders/$id/status'
  id:
    | '__root__'
    | '/'
    | '/install'
    | '/names'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/api/price'
    | '/api/quote'
    | '/gallery/holy-ship'
    | '/order/thank-you'
    | '/api/admin/orders'
    | '/api/orders/approve'
    | '/api/stripe/webhook'
    | '/api/admin/orders/$id/send-proof'
    | '/api/admin/orders/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallRoute: typeof InstallRoute
  NamesRoute: typeof NamesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPriceRoute: typeof ApiPriceRoute
  ApiQuoteRoute: typeof ApiQuoteRoute
  GalleryHolyShipRoute: typeof GalleryHolyShipRoute
  OrderThankYouRoute: typeof OrderThankYouRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRouteWithChildren
  ApiOrdersApproveRoute: typeof ApiOrdersApproveRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/thank-you': {
      id: '/order/thank-you'
      path: '/order/thank-you'
      fullPath: '/order/thank-you'
      preLoaderRoute: typeof OrderThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/holy-ship': {
      id: '/gallery/holy-ship'
      path: '/gallery/holy-ship'
      fullPath: '/gallery/holy-ship'
      preLoaderRoute: typeof GalleryHolyShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote': {
      id: '/api/quote'
      path: '/api/quote'
      fullPath: '/api/quote'
      preLoaderRoute: typeof ApiQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price': {
      id: '/api/price'
      path: '/api/price'
      fullPath: '/api/price'
      preLoaderRoute: typeof ApiPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/approve': {
      id: '/api/orders/approve'
      path: '/api/orders/approve'
      fullPath: '/api/orders/approve'
      preLoaderRoute: typeof ApiOrdersApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/$id/status': {
      id: '/api/admin/orders/$id/status'
      path: '/$id/status'
      fullPath: '/api/admin/orders/$id/status'
      preLoaderRoute: typeof ApiAdminOrdersIdStatusRouteImport
      parentRoute: typeof ApiAdminOrdersRoute
    }
    '/api/admin/orders/$id/send-proof': {
      id: '/api/admin/orders/$id/send-proof'
      path: '/$id/send-proof'
      fullPath: '/api/admin/orders/$id/send-proof'
      preLoaderRoute: typeof ApiAdminOrdersIdSendProofRouteImport
      parentRoute: typeof ApiAdminOrdersRoute
    }
  }
}

interface ApiAdminOrdersRouteChildren {
  ApiAdminOrdersIdSendProofRoute: typeof ApiAdminOrdersIdSendProofRoute
  ApiAdminOrdersIdStatusRoute: typeof ApiAdminOrdersIdStatusRoute
}

const ApiAdminOrdersRouteChildren: ApiAdminOrdersRouteChildren = {
  ApiAdminOrdersIdSendProofRoute: ApiAdminOrdersIdSendProofRoute,
  ApiAdminOrdersIdStatusRoute: ApiAdminOrdersIdStatusRoute,
}

const ApiAdminOrdersRouteWithChildren = ApiAdminOrdersRoute._addFileChildren(
  ApiAdminOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallRoute: InstallRoute,
  NamesRoute: NamesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPriceRoute: ApiPriceRoute,
  ApiQuoteRoute: ApiQuoteRoute,
  GalleryHolyShipRoute: GalleryHolyShipRoute,
  OrderThankYouRoute: OrderThankYouRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRouteWithChildren,
  ApiOrdersApproveRoute: ApiOrdersApproveRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
